# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rytdinterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(412, 689)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.downloadVideoAudioButton = QtWidgets.QPushButton(self.centralwidget)
        self.downloadVideoAudioButton.setEnabled(False)
        self.downloadVideoAudioButton.setGeometry(QtCore.QRect(20, 490, 371, 41))
        self.downloadVideoAudioButton.setObjectName("downloadVideoAudioButton")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 620, 371, 21))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.ytlinkLine = QtWidgets.QLineEdit(self.centralwidget)
        self.ytlinkLine.setGeometry(QtCore.QRect(20, 40, 281, 20))
        self.ytlinkLine.setObjectName("ytlinkLine")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 281, 16))
        self.label.setObjectName("label")
        self.thumbnailDownloadButton = QtWidgets.QPushButton(self.centralwidget)
        self.thumbnailDownloadButton.setEnabled(False)
        self.thumbnailDownloadButton.setGeometry(QtCore.QRect(240, 280, 141, 31))
        self.thumbnailDownloadButton.setObjectName("thumbnailDownloadButton")
        self.applylinkButton = QtWidgets.QPushButton(self.centralwidget)
        self.applylinkButton.setGeometry(QtCore.QRect(310, 40, 81, 23))
        self.applylinkButton.setObjectName("applylinkButton")
        self.thumbnailLabel = QtWidgets.QLabel(self.centralwidget)
        self.thumbnailLabel.setGeometry(QtCore.QRect(30, 70, 351, 201))
        self.thumbnailLabel.setStyleSheet("border-style: solid;\n"
"border-color: rgb(77, 0, 59);\n"
"border-width: 1px;")
        self.thumbnailLabel.setText("")
        self.thumbnailLabel.setScaledContents(True)
        self.thumbnailLabel.setObjectName("thumbnailLabel")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 380, 371, 91))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pathComboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.pathComboBox.setGeometry(QtCore.QRect(10, 20, 351, 22))
        self.pathComboBox.setObjectName("pathComboBox")
        self.addpathButton = QtWidgets.QPushButton(self.groupBox_2)
        self.addpathButton.setGeometry(QtCore.QRect(10, 50, 111, 31))
        self.addpathButton.setObjectName("addpathButton")
        self.removepathButton = QtWidgets.QPushButton(self.groupBox_2)
        self.removepathButton.setGeometry(QtCore.QRect(130, 50, 101, 31))
        self.removepathButton.setObjectName("removepathButton")
        self.downloadVideoButton = QtWidgets.QPushButton(self.centralwidget)
        self.downloadVideoButton.setEnabled(False)
        self.downloadVideoButton.setGeometry(QtCore.QRect(20, 530, 371, 41))
        self.downloadVideoButton.setObjectName("downloadVideo")
        self.nameLine = QtWidgets.QLineEdit(self.centralwidget)
        self.nameLine.setGeometry(QtCore.QRect(20, 340, 361, 21))
        self.nameLine.setObjectName("nameLine")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 320, 361, 16))
        self.label_2.setObjectName("label_2")
        self.downloadAudioButton = QtWidgets.QPushButton(self.centralwidget)
        self.downloadAudioButton.setEnabled(False)
        self.downloadAudioButton.setGeometry(QtCore.QRect(20, 570, 371, 41))
        self.downloadAudioButton.setObjectName("downloadAudio")
        self.versionLabel = QtWidgets.QLabel(self.centralwidget)
        self.versionLabel.setGeometry(QtCore.QRect(340, 0, 47, 13))
        self.versionLabel.setObjectName("versionLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 412, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EasyVideoDownloader"))
        self.downloadVideoAudioButton.setToolTip(_translate("MainWindow",
                                                            "Скачать выбранное видео (MP4).\n"
                                                            "При отсутствии FFmpeg видеоряд и аудиоряд "
                                                            "будут скачаны отдельными файлами (MP4 и M4A)."))
        self.downloadVideoAudioButton.setText(_translate("MainWindow", "Скачать"))
        self.label.setText(_translate("MainWindow", "Ссылка на видео"))
        self.thumbnailDownloadButton.setText(_translate("MainWindow", "Скачать превью"))
        self.applylinkButton.setText(_translate("MainWindow", "Применить"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Путь скачивания видео"))
        self.addpathButton.setText(_translate("MainWindow", "Добавить путь"))
        self.removepathButton.setText(_translate("MainWindow", "Удалить путь"))
        self.downloadVideoButton.setToolTip(_translate("MainWindow",
                                                       "Скачать только видеоряд (MP4)"))
        self.downloadVideoButton.setText(_translate("MainWindow", "Скачать только видео"))
        self.label_2.setText(_translate("MainWindow", "Название видео"))
        self.downloadAudioButton.setToolTip(_translate("MainWindow",
                                                       "Скачать только аудиоряд (MP3)\n"
                                                       "При отсутствии FFmpeg аудиоряд будет скачен в формате M4A."))
        self.downloadAudioButton.setText(_translate("MainWindow", "Скачать только аудио"))
        self.versionLabel.setText(_translate("MainWindow", "ver. 1.0"))

    def updateButtons(self, enableStatus):
        self.thumbnailDownloadButton.setEnabled(enableStatus)
        self.downloadVideoAudioButton.setEnabled(enableStatus)
        self.downloadVideoButton.setEnabled(enableStatus)
        self.downloadAudioButton.setEnabled(enableStatus)
